package collections

const (
	EndpointCollections = "/collections"
)

// Collection relationship types
const (
	RelationshipAutogeneratedGraphs   = "autogenerated_graphs"
	RelationshipComments              = "comments"
	RelationshipDomains               = "domains"
	RelationshipFiles                 = "files"
	RelationshipIPAddresses           = "ip_addresses"
	RelationshipOwner                 = "owner"
	RelationshipReferences            = "references"
	RelationshipRelatedCollections    = "related_collections"     // VT Enterprise only
	RelationshipRelatedReferences     = "related_references"      // VT Enterprise only
	RelationshipThreatActors          = "threat_actors"           // VT Enterprise only
	RelationshipURLs                  = "urls"
)
