package collections

import (
	"context"
	"fmt"

	"github.com/deploymenttheory/go-api-sdk-virustotal/virustotal/interfaces"
)

type (
	// CollectionsServiceInterface defines the interface for collection operations
	//
	// VirusTotal API docs: https://docs.virustotal.com/reference
	CollectionsServiceInterface interface {
		// CreateCollection creates a new collection
		//
		// Collections allow you to organize IOCs (Indicators of Compromise) from VirusTotal,
		// including files, URLs, domains, and IP addresses. You can create a collection using
		// either relationship descriptors or raw text containing IOCs. Tags starting with #
		// are automatically extracted from the description.
		//
		// VirusTotal API docs: https://docs.virustotal.com/reference/collections-create
		CreateCollection(ctx context.Context, req *CreateCollectionRequest) (*CollectionResponse, *interfaces.Response, error)

		// GetCollection retrieves a collection by ID
		//
		// Returns detailed information about a collection including its name, description,
		// creation/modification dates, and related IOCs. Use the relationships endpoint
		// to retrieve the actual items in the collection.
		//
		// VirusTotal API docs: https://docs.virustotal.com/reference/collections-get
		GetCollection(ctx context.Context, collectionID string) (*CollectionResponse, *interfaces.Response, error)

		// UpdateCollection updates a collection's attributes or adds new elements
		//
		// Allows updating a collection's name and description, or adding new IOCs using raw text.
		// To add IOCs using relationship descriptors, use AddItemsToCollection instead.
		//
		// VirusTotal API docs: https://docs.virustotal.com/reference/collections-update
		UpdateCollection(ctx context.Context, collectionID string, req *UpdateCollectionRequest) (*CollectionResponse, *interfaces.Response, error)

		// DeleteCollection deletes a collection
		//
		// Permanently removes a collection and all its contents. This operation cannot be undone.
		//
		// VirusTotal API docs: https://docs.virustotal.com/reference/collections-delete
		DeleteCollection(ctx context.Context, collectionID string) (*DeleteCollectionResponse, *interfaces.Response, error)

		// GetCommentsOnCollection retrieves comments on a collection
		//
		// Returns a list of comments posted by the VirusTotal community about the collection.
		// Comments may include tags extracted from words starting with #. Results are paginated.
		//
		// VirusTotal API docs: https://docs.virustotal.com/reference/collections-comments
		GetCommentsOnCollection(ctx context.Context, collectionID string, opts *GetRelatedObjectsOptions) (*CommentsResponse, *interfaces.Response, error)

		// AddCommentToCollection adds a comment to a collection
		//
		// Posts a comment for a collection. Words starting with # in the comment text are automatically
		// converted to tags. Returns the created comment object with its assigned ID, creation date, and extracted tags.
		//
		// VirusTotal API docs: https://docs.virustotal.com/reference/collections-comments-create
		AddCommentToCollection(ctx context.Context, collectionID string, comment string) (*AddCommentResponse, *interfaces.Response, error)

		// GetObjectsRelatedToCollection retrieves objects related to a collection
		//
		// Returns objects related to a collection based on the specified relationship type.
		// Supported relationships include: autogenerated_graphs, comments, domains, files, ip_addresses,
		// owner, references, urls, and VT Enterprise-only relationships like related_collections,
		// related_references, and threat_actors.
		//
		// Note: Some relationships require VT Enterprise license. Public API relationships include:
		// autogenerated_graphs, comments, domains, files, ip_addresses, owner, references, urls.
		// Enterprise-only relationships include: related_collections, related_references, threat_actors.
		//
		// VirusTotal API docs: https://docs.virustotal.com/reference/get-collections-relationship
		GetObjectsRelatedToCollection(ctx context.Context, collectionID string, relationship string, opts *GetRelatedObjectsOptions) (*RelatedObjectsResponse, *interfaces.Response, error)

		// GetObjectDescriptorsRelatedToCollection retrieves object descriptors (IDs only) related to a collection
		//
		// Returns lightweight object descriptors with just IDs and context attributes instead of full objects.
		// This is more efficient when you only need to know which objects are related without fetching all attributes.
		// Supported relationships are the same as GetObjectsRelatedToCollection.
		//
		// Note: Some relationships require VT Enterprise license. Public API relationships include:
		// autogenerated_graphs, comments, domains, files, ip_addresses, owner, references, urls.
		// Enterprise-only relationships include: related_collections, related_references, threat_actors.
		//
		// VirusTotal API docs: https://docs.virustotal.com/reference/get-collections-relationship-descriptor
		GetObjectDescriptorsRelatedToCollection(ctx context.Context, collectionID string, relationship string, opts *GetRelatedObjectsOptions) (*ObjectDescriptorsResponse, *interfaces.Response, error)

		// AddItemsToCollection adds new items to a collection under the specified relationship
		//
		// Adds IOCs to a collection using relationship descriptors. For URLs, you can specify either
		// the URL ID (SHA-256 hash) or the actual URL string. For other IOC types (domains, files, IPs),
		// use the appropriate identifier.
		//
		// VirusTotal API docs: https://docs.virustotal.com/reference/collections-add-element
		AddItemsToCollection(ctx context.Context, collectionID string, relationship string, req *AddItemsRequest) (*AddItemsResponse, *interfaces.Response, error)

		// DeleteItemsFromCollection deletes items from a collection under the specified relationship
		//
		// Removes IOCs from a collection using relationship descriptors. For URLs, you can specify either
		// the URL ID (SHA-256 hash) or the actual URL string. For other IOC types (domains, files, IPs),
		// use the appropriate identifier.
		//
		// VirusTotal API docs: https://docs.virustotal.com/reference/collections-delete-element
		DeleteItemsFromCollection(ctx context.Context, collectionID string, relationship string, req *DeleteItemsRequest) (*DeleteItemsResponse, *interfaces.Response, error)
	}

	// Service handles communication with the Collections
	// related methods of the VirusTotal API.
	//
	// VirusTotal API docs: https://docs.virustotal.com/reference/collections-create
	Service struct {
		client interfaces.HTTPClient
	}
)

var _ CollectionsServiceInterface = (*Service)(nil)

func NewService(client interfaces.HTTPClient) *Service {
	return &Service{
		client: client,
	}
}

// =============================================================================
// Collection CRUD Operations
// =============================================================================

// CreateCollection creates a new collection
// URL: POST https://www.virustotal.com/api/v3/collections
// Body: JSON with collection name, description, and relationships or raw_items
// https://docs.virustotal.com/reference/collections-create
func (s *Service) CreateCollection(ctx context.Context, req *CreateCollectionRequest) (*CollectionResponse, *interfaces.Response, error) {
	if err := ValidateCreateCollectionRequest(req); err != nil {
		return nil, nil, err
	}

	endpoint := EndpointCollections
	headers := map[string]string{
		"Accept":       "application/json",
		"Content-Type": "application/json",
	}

	var result CollectionResponse
	resp, err := s.client.Post(ctx, endpoint, req, headers, &result)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// GetCollection retrieves a collection by ID
// URL: GET https://www.virustotal.com/api/v3/collections/{id}
// https://docs.virustotal.com/reference/collections-get
func (s *Service) GetCollection(ctx context.Context, collectionID string) (*CollectionResponse, *interfaces.Response, error) {
	if err := ValidateCollectionID(collectionID); err != nil {
		return nil, nil, err
	}

	endpoint := fmt.Sprintf("%s/%s", EndpointCollections, collectionID)
	headers := map[string]string{
		"Accept": "application/json",
	}

	var result CollectionResponse
	resp, err := s.client.Get(ctx, endpoint, nil, headers, &result)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// UpdateCollection updates a collection's attributes or adds new elements
// URL: PATCH https://www.virustotal.com/api/v3/collections/{id}
// Body: JSON with updated name/description or raw_items
// https://docs.virustotal.com/reference/collections-update
func (s *Service) UpdateCollection(ctx context.Context, collectionID string, req *UpdateCollectionRequest) (*CollectionResponse, *interfaces.Response, error) {
	if err := ValidateCollectionID(collectionID); err != nil {
		return nil, nil, err
	}
	if err := ValidateUpdateCollectionRequest(req); err != nil {
		return nil, nil, err
	}

	endpoint := fmt.Sprintf("%s/%s", EndpointCollections, collectionID)
	headers := map[string]string{
		"Accept":       "application/json",
		"Content-Type": "application/json",
	}

	var result CollectionResponse
	resp, err := s.client.Patch(ctx, endpoint, req, headers, &result)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteCollection deletes a collection
// URL: DELETE https://www.virustotal.com/api/v3/collections/{id}
// https://docs.virustotal.com/reference/collections-delete
func (s *Service) DeleteCollection(ctx context.Context, collectionID string) (*DeleteCollectionResponse, *interfaces.Response, error) {
	if err := ValidateCollectionID(collectionID); err != nil {
		return nil, nil, err
	}

	endpoint := fmt.Sprintf("%s/%s", EndpointCollections, collectionID)
	headers := map[string]string{
		"Accept": "application/json",
	}

	var result DeleteCollectionResponse
	resp, err := s.client.Delete(ctx, endpoint, nil, headers, &result)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// =============================================================================
// Comment Operations
// =============================================================================

// GetCommentsOnCollection retrieves comments on a collection
// URL: GET https://www.virustotal.com/api/v3/collections/{id}/comments
// Query Params: limit (optional), cursor (optional)
// https://docs.virustotal.com/reference/collections-comments
func (s *Service) GetCommentsOnCollection(ctx context.Context, collectionID string, opts *GetRelatedObjectsOptions) (*CommentsResponse, *interfaces.Response, error) {
	if err := ValidateCollectionID(collectionID); err != nil {
		return nil, nil, err
	}

	endpoint := fmt.Sprintf("%s/%s/comments", EndpointCollections, collectionID)
	headers := map[string]string{
		"Accept": "application/json",
	}

	queryParams := make(map[string]string)
	if opts != nil {
		if opts.Limit > 0 {
			queryParams["limit"] = fmt.Sprintf("%d", opts.Limit)
		}
		if opts.Cursor != "" {
			queryParams["cursor"] = opts.Cursor
		}
	}

	var result CommentsResponse
	resp, err := s.client.Get(ctx, endpoint, queryParams, headers, &result)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// AddCommentToCollection adds a comment to a collection
// URL: POST https://www.virustotal.com/api/v3/collections/{id}/comments
// Body: JSON with comment text (words starting with # become tags)
// https://docs.virustotal.com/reference/collections-comments-create
func (s *Service) AddCommentToCollection(ctx context.Context, collectionID string, comment string) (*AddCommentResponse, *interfaces.Response, error) {
	if err := ValidateCollectionID(collectionID); err != nil {
		return nil, nil, err
	}
	if err := ValidateCommentText(comment); err != nil {
		return nil, nil, err
	}

	req := &AddCommentRequest{
		Data: AddCommentData{
			Type: "comment",
			Attributes: AddCommentAttributes{
				Text: comment,
			},
		},
	}

	endpoint := fmt.Sprintf("%s/%s/comments", EndpointCollections, collectionID)
	headers := map[string]string{
		"Accept":       "application/json",
		"Content-Type": "application/json",
	}

	var result AddCommentResponse
	resp, err := s.client.Post(ctx, endpoint, req, headers, &result)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// =============================================================================
// Relationship Operations
// =============================================================================

// GetObjectsRelatedToCollection retrieves objects related to a collection
// URL: GET https://www.virustotal.com/api/v3/collections/{id}/{relationship}
// Query Params: limit (optional), cursor (optional)
// Note: Some relationships require VT Enterprise license (related_collections, related_references, threat_actors)
// https://docs.virustotal.com/reference/get-collections-relationship
func (s *Service) GetObjectsRelatedToCollection(ctx context.Context, collectionID string, relationship string, opts *GetRelatedObjectsOptions) (*RelatedObjectsResponse, *interfaces.Response, error) {
	if err := ValidateCollectionID(collectionID); err != nil {
		return nil, nil, err
	}
	if err := ValidateRelationship(relationship); err != nil {
		return nil, nil, err
	}

	endpoint := fmt.Sprintf("%s/%s/%s", EndpointCollections, collectionID, relationship)
	headers := map[string]string{
		"Accept": "application/json",
	}

	queryParams := make(map[string]string)
	if opts != nil {
		if opts.Limit > 0 {
			queryParams["limit"] = fmt.Sprintf("%d", opts.Limit)
		}
		if opts.Cursor != "" {
			queryParams["cursor"] = opts.Cursor
		}
	}

	var result RelatedObjectsResponse
	resp, err := s.client.Get(ctx, endpoint, queryParams, headers, &result)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// GetObjectDescriptorsRelatedToCollection retrieves object descriptors related to a collection
// URL: GET https://www.virustotal.com/api/v3/collections/{id}/relationships/{relationship}
// Query Params: limit (optional), cursor (optional)
// Note: Some relationships require VT Enterprise license (related_collections, related_references, threat_actors)
// https://docs.virustotal.com/reference/get-collections-relationship-descriptor
func (s *Service) GetObjectDescriptorsRelatedToCollection(ctx context.Context, collectionID string, relationship string, opts *GetRelatedObjectsOptions) (*ObjectDescriptorsResponse, *interfaces.Response, error) {
	if err := ValidateCollectionID(collectionID); err != nil {
		return nil, nil, err
	}
	if err := ValidateRelationship(relationship); err != nil {
		return nil, nil, err
	}

	endpoint := fmt.Sprintf("%s/%s/relationships/%s", EndpointCollections, collectionID, relationship)
	headers := map[string]string{
		"Accept": "application/json",
	}

	queryParams := make(map[string]string)
	if opts != nil {
		if opts.Limit > 0 {
			queryParams["limit"] = fmt.Sprintf("%d", opts.Limit)
		}
		if opts.Cursor != "" {
			queryParams["cursor"] = opts.Cursor
		}
	}

	var result ObjectDescriptorsResponse
	resp, err := s.client.Get(ctx, endpoint, queryParams, headers, &result)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// =============================================================================
// Item Management Operations
// =============================================================================

// AddItemsToCollection adds new items to a collection
// URL: POST https://www.virustotal.com/api/v3/collections/{id}/{relationship}
// Body: JSON array of relationship items (for URLs: use id or url field)
// https://docs.virustotal.com/reference/collections-add-element
func (s *Service) AddItemsToCollection(ctx context.Context, collectionID string, relationship string, req *AddItemsRequest) (*AddItemsResponse, *interfaces.Response, error) {
	if err := ValidateCollectionID(collectionID); err != nil {
		return nil, nil, err
	}
	if err := ValidateRelationship(relationship); err != nil {
		return nil, nil, err
	}
	if err := ValidateAddItemsRequest(req); err != nil {
		return nil, nil, err
	}

	endpoint := fmt.Sprintf("%s/%s/%s", EndpointCollections, collectionID, relationship)
	headers := map[string]string{
		"Accept":       "application/json",
		"Content-Type": "application/json",
	}

	var result AddItemsResponse
	resp, err := s.client.Post(ctx, endpoint, req, headers, &result)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}

// DeleteItemsFromCollection deletes items from a collection
// URL: DELETE https://www.virustotal.com/api/v3/collections/{id}/{relationship}
// Body: JSON array of relationship items (for URLs: use id or url field)
// https://docs.virustotal.com/reference/collections-delete-element
func (s *Service) DeleteItemsFromCollection(ctx context.Context, collectionID string, relationship string, req *DeleteItemsRequest) (*DeleteItemsResponse, *interfaces.Response, error) {
	if err := ValidateCollectionID(collectionID); err != nil {
		return nil, nil, err
	}
	if err := ValidateRelationship(relationship); err != nil {
		return nil, nil, err
	}
	if err := ValidateDeleteItemsRequest(req); err != nil {
		return nil, nil, err
	}

	endpoint := fmt.Sprintf("%s/%s/%s", EndpointCollections, collectionID, relationship)
	headers := map[string]string{
		"Accept":       "application/json",
		"Content-Type": "application/json",
	}

	var result DeleteItemsResponse
	resp, err := s.client.DeleteWithBody(ctx, endpoint, req, headers, &result)
	if err != nil {
		return nil, resp, err
	}

	return &result, resp, nil
}
