package collections

import (
	"github.com/deploymenttheory/go-api-sdk-virustotal/virustotal/shared_models"
)

// =============================================================================
// Common Structures
// =============================================================================

type Links = shared_models.ObjectLinks
type RelatedLinks = shared_models.Links
type Meta = shared_models.Meta

// =============================================================================
// Collection Models
// =============================================================================

// CollectionResponse represents a collection object response
type CollectionResponse struct {
	Data Collection `json:"data"`
}

// Collection represents a VirusTotal collection
type Collection struct {
	Type          string                `json:"type"`
	ID            string                `json:"id"`
	Links         Links                 `json:"links,omitempty"`
	Attributes    CollectionAttributes  `json:"attributes"`
	Relationships CollectionRelationships `json:"relationships,omitempty"`
}

// CollectionAttributes contains collection attributes
type CollectionAttributes struct {
	Name                string `json:"name"`
	Description         string `json:"description,omitempty"`
	CreationDate        int64  `json:"creation_date,omitempty"`
	ModificationDate    int64  `json:"modification_date,omitempty"`
}

// CollectionRelationships contains relationships to IOCs in the collection
type CollectionRelationships struct {
	Domains               *RelationshipData `json:"domains,omitempty"`
	Files                 *RelationshipData `json:"files,omitempty"`
	IPAddresses           *RelationshipData `json:"ip_addresses,omitempty"`
	URLs                  *RelationshipData `json:"urls,omitempty"`
	AutogeneratedGraphs   *RelationshipData `json:"autogenerated_graphs,omitempty"`
	Comments              *RelationshipData `json:"comments,omitempty"`
	Owner                 *RelationshipData `json:"owner,omitempty"`
	References            *RelationshipData `json:"references,omitempty"`
	RelatedCollections    *RelationshipData `json:"related_collections,omitempty"`
	RelatedReferences     *RelationshipData `json:"related_references,omitempty"`
	ThreatActors          *RelationshipData `json:"threat_actors,omitempty"`
}

// RelationshipData represents relationship data
type RelationshipData struct {
	Data  []RelationshipItem `json:"data"`
	Links RelatedLinks       `json:"links,omitempty"`
}

// RelationshipItem represents a single relationship item
type RelationshipItem struct {
	Type string `json:"type"`
	ID   string `json:"id,omitempty"`
	URL  string `json:"url,omitempty"` // For URL relationships, can use either ID or URL
}

// =============================================================================
// Create Collection Models
// =============================================================================

// CreateCollectionRequest represents a request to create a new collection
type CreateCollectionRequest struct {
	Data CreateCollectionData `json:"data"`
}

// CreateCollectionData contains the collection data for creation
type CreateCollectionData struct {
	Type          string                       `json:"type"`
	Attributes    CreateCollectionAttributes   `json:"attributes"`
	Relationships *CollectionRelationships     `json:"relationships,omitempty"`
	RawItems      string                       `json:"raw_items,omitempty"`
}

// CreateCollectionAttributes contains attributes for creating a collection
type CreateCollectionAttributes struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
}

// =============================================================================
// Update Collection Models
// =============================================================================

// UpdateCollectionRequest represents a request to update a collection
type UpdateCollectionRequest struct {
	Data UpdateCollectionData `json:"data"`
}

// UpdateCollectionData contains the collection data for update
type UpdateCollectionData struct {
	Type       string                       `json:"type"`
	Attributes *UpdateCollectionAttributes  `json:"attributes,omitempty"`
	RawItems   string                       `json:"raw_items,omitempty"`
}

// UpdateCollectionAttributes contains attributes that can be updated
type UpdateCollectionAttributes struct {
	Name        string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
}

// =============================================================================
// Delete Collection Response
// =============================================================================

// DeleteCollectionResponse represents the response from deleting a collection
// Note: The API returns an empty object {} on success
type DeleteCollectionResponse struct {
	Data *DeleteCollectionData `json:"data,omitempty"`
}

// DeleteCollectionData contains the deleted collection ID (may be empty)
type DeleteCollectionData struct {
	Type string `json:"type,omitempty"`
	ID   string `json:"id,omitempty"`
}

// =============================================================================
// Comments Models
// =============================================================================

// CommentsResponse represents a list of comments
type CommentsResponse struct {
	Data  []Comment    `json:"data"`
	Links RelatedLinks `json:"links,omitempty"`
	Meta  Meta         `json:"meta,omitempty"`
}

// Comment represents a comment object
type Comment struct {
	Type       string            `json:"type"`
	ID         string            `json:"id"`
	Links      Links             `json:"links,omitempty"`
	Attributes CommentAttributes `json:"attributes"`
}

// CommentAttributes contains comment attributes
type CommentAttributes struct {
	Date int64             `json:"date"`
	HTML string            `json:"html"`
	Text string            `json:"text"`
	Tags []string          `json:"tags,omitempty"`
	Votes CommentVotes     `json:"votes,omitempty"`
}

// CommentVotes represents votes on a comment
type CommentVotes struct {
	Abuse    int `json:"abuse,omitempty"`
	Negative int `json:"negative,omitempty"`
	Positive int `json:"positive,omitempty"`
}

// AddCommentRequest represents a request to add a comment
type AddCommentRequest struct {
	Data AddCommentData `json:"data"`
}

// AddCommentData contains the comment data
type AddCommentData struct {
	Type       string                   `json:"type"`
	Attributes AddCommentAttributes     `json:"attributes"`
}

// AddCommentAttributes contains the comment text
type AddCommentAttributes struct {
	Text string `json:"text"`
}

// AddCommentResponse represents the response from adding a comment
type AddCommentResponse struct {
	Data Comment `json:"data"`
}

// =============================================================================
// Related Objects Models
// =============================================================================

// RelatedObjectsResponse represents related objects response
type RelatedObjectsResponse struct {
	Data  []RelatedObject `json:"data"`
	Links RelatedLinks    `json:"links,omitempty"`
	Meta  Meta            `json:"meta,omitempty"`
}

// RelatedObject represents a related object
type RelatedObject struct {
	Type              string                 `json:"type"`
	ID                string                 `json:"id"`
	Links             Links                  `json:"links,omitempty"`
	Attributes        map[string]interface{} `json:"attributes,omitempty"`
	ContextAttributes map[string]interface{} `json:"context_attributes,omitempty"`
}

// ObjectDescriptorsResponse represents object descriptors response
type ObjectDescriptorsResponse struct {
	Data  []ObjectDescriptor `json:"data"`
	Links RelatedLinks       `json:"links,omitempty"`
	Meta  Meta               `json:"meta,omitempty"`
}

// ObjectDescriptor represents an object descriptor
type ObjectDescriptor struct {
	Type              string                 `json:"type"`
	ID                string                 `json:"id"`
	Links             Links                  `json:"links,omitempty"`
	ContextAttributes map[string]interface{} `json:"context_attributes,omitempty"`
}

// =============================================================================
// Add/Delete Items Models
// =============================================================================

// AddItemsRequest represents a request to add items to a collection
type AddItemsRequest struct {
	Data []RelationshipItem `json:"data"`
}

// AddItemsResponse represents the response from adding items
// Note: The API returns an empty object {} on success
type AddItemsResponse struct {
	Data *AddItemsData `json:"data,omitempty"`
}

// AddItemsData contains the response data for added items (may be empty)
type AddItemsData struct {
	Type string `json:"type,omitempty"`
	ID   string `json:"id,omitempty"`
}

// DeleteItemsRequest represents a request to delete items from a collection
type DeleteItemsRequest struct {
	Data []RelationshipItem `json:"data"`
}

// DeleteItemsResponse represents the response from deleting items
// Note: The API returns an empty object {} on success
type DeleteItemsResponse struct {
	Data *DeleteItemsData `json:"data,omitempty"`
}

// DeleteItemsData contains the response data for deleted items (may be empty)
type DeleteItemsData struct {
	Type string `json:"type,omitempty"`
	ID   string `json:"id,omitempty"`
}

// =============================================================================
// Options
// =============================================================================

// GetRelatedObjectsOptions contains options for retrieving related objects
type GetRelatedObjectsOptions struct {
	Limit  int    `json:"limit,omitempty"`
	Cursor string `json:"cursor,omitempty"`
}
